apiVersion: ''
kind: ''
spec: {}
endpoints:
  - name: endpoint-1
    service:
      port: 8080
      basePath: /
    type: REST
    displayName: endpoint-1
    networkVisibilities:
      - Public
      - Organization
      - Project
    schemaFilePath: openapi.yaml
